version: '3'
services:
  nodejs-app:
    build:
      context: .   # 指定Dockerfile所在的目录
    ports:
      - "3000:3000"  # 映射Node.js应用程序的端口
    links:
      - mongo  # 连接到名为mongo的MongoDB容器
      - redis  # 连接到名为redis的Redis容器

  mongo:
    image: mongo
    ports:
      - "27017:27017"  # 映射MongoDB的端口

  redis:
    image: redis
    ports:
      - "6379:6379"  # 映射Redis的端口
