version: '3.8'

services:
  # Node.js 应用服务
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    depends_on:
      - mongodb
      - redis
    networks:
      - Lulab-network

  # MongoDB 服务
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - Lulab-network

  # Redis 服务
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - Lulab-network

networks:
  Lulab-network:
    driver: bridge